
package universidadejemp.Vistas;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import universidadejemp.AccesoADatos.InscripcionData;
import universidadejemp.AccesoADatos.MateriaData;
import universidadejemp.Entidades.Alumno;
import universidadejemp.Entidades.Materia;

/**
 *
 * @author Jorge
 */
public class ConsultaDeAlumnosPorMateria extends javax.swing.JInternalFrame {

    private DefaultTableModel tableModel;
    
    public ConsultaDeAlumnosPorMateria() {
        initComponents();
        configurarComponentesAdicionales();
        
    }
    private void configurarComponentesAdicionales() {
        // Configurar el modelo de la tabla
        tableModel = new DefaultTableModel(
            new Object[][]{},
            new String[]{"ID", "DNI", "Apellido", "Nombre"}
        );
        jTable1.setModel(tableModel);

        // Agregar ActionListeners a los componentes
        jComboBox1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cargarAlumnosPorMateria();
            }
        });
        cargarMaterias();
    }
    private void cargarMaterias() {
        MateriaData materiaData = new MateriaData();
        List<Materia> materias = materiaData.listarMaterias();

        for (Materia materia : materias) {
            jComboBox1.addItem(materia.getNombre());
        }
    }

    private void cargarAlumnosPorMateria() {
        String materiaSeleccionada = (String) jComboBox1.getSelectedItem();

        MateriaData materiaData = new MateriaData();
        List<Materia> materias = materiaData.listarMaterias();
        int idMateria = -1;
        for (Materia materia : materias) {
            if (materia.getNombre().equals(materiaSeleccionada)) {
                idMateria = materia.getIdMateria();
                break;
            }
        }

        if (idMateria == -1) {
            JOptionPane.showMessageDialog(this, "Materia no encontrada");
            return;
        }

        tableModel.setRowCount(0);

        InscripcionData inscripcionData = new InscripcionData();
        List<Alumno> alumnos = inscripcionData.obtenerAlumnosPorMateria(idMateria);

        for (Alumno alumno : alumnos) {
            tableModel.addRow(new Object[]{alumno.getIdAlumno(), alumno.getDni(), alumno.getApellido(), alumno.getNombre()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Seleccione una Materia:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
