/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package universidadejemp.Vistas;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Facu
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(700, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icono=new ImageIcon (getClass().getResource("/universidadejemp/Recursos/ulpfondo.jpg"));
        Image fondo=icono.getImage();
        escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent (Graphics graf){
                graf.drawImage(fondo, 0, 0, getWidth(), getHeight(),this);
            }

        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAlumnos = new javax.swing.JMenu();
        jmMaterias = new javax.swing.JMenu();
        jmFormMaterias = new javax.swing.JMenuItem();
        jmInscripcion = new javax.swing.JMenu();
        jmNotas = new javax.swing.JMenu();
        jmSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(6, 43, 98));
        jMenuBar1.setForeground(new java.awt.Color(5, 26, 40));
        jMenuBar1.setOpaque(true);

        jmAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidadejemp/Recursos/alumnos.png"))); // NOI18N
        jmAlumnos.setText("Alumnos");
        jmAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAlumnosActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmAlumnos);

        jmMaterias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidadejemp/Recursos/libros.png"))); // NOI18N
        jmMaterias.setText("Materias");
        jmMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMateriasActionPerformed(evt);
            }
        });

        jmFormMaterias.setText("Formulario de Materias");
        jmFormMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFormMateriasActionPerformed(evt);
            }
        });
        jmMaterias.add(jmFormMaterias);

        jMenuBar1.add(jmMaterias);

        jmInscripcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidadejemp/Recursos/contrato.png"))); // NOI18N
        jmInscripcion.setText("Inscripción");
        jMenuBar1.add(jmInscripcion);

        jmNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidadejemp/Recursos/notas.png"))); // NOI18N
        jmNotas.setText("Notas");
        jMenuBar1.add(jmNotas);

        jmSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidadejemp/Recursos/cerrar-sesion.png"))); // NOI18N
        jmSalir.setText("Salir");
        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAlumnosActionPerformed
escritorio.removeAll();
escritorio.repaint();


    }//GEN-LAST:event_jmAlumnosActionPerformed

    private void jmMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMateriasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
    }//GEN-LAST:event_jmMateriasActionPerformed

    private void jmFormMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFormMateriasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        GestionMaterias form = new GestionMaterias();
        form.setVisible(true);
        form.getContentPane().setBackground(new Color(87,149,221));
        escritorio.add(form);
    }//GEN-LAST:event_jmFormMateriasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmAlumnos;
    private javax.swing.JMenuItem jmFormMaterias;
    private javax.swing.JMenu jmInscripcion;
    private javax.swing.JMenu jmMaterias;
    private javax.swing.JMenu jmNotas;
    private javax.swing.JMenu jmSalir;
    // End of variables declaration//GEN-END:variables
}
